### ISSUE TITLE
Customization of visual components in MolArt

### ISSUE THREAD

**Issue by pdtouch** [cusbg/MolArt#31]
I intend to make the following modification to the MolArt web GUI and greatly appreciate any guidance on the right way to go about doing the same.

The filtering of variants by different categories (Disease, Predicted deleterious,...) under the Filter consequence and Filter data source sections of Variants need to be changed to simple checkboxes allowing multiple check boxes the user chooses to check at a time to show only variations of the checked categories to be plotted in the variant plot area. Existing  filtering interface does not toggle category selection plots with single clicks which is somewhat confusing.

**Comment by davidhoksza** [comment]
There is now `variantFilterDefaultBehavior` option which can be set to false in which the variant consequence filter works as ordinary list of checkboxes.

**Comment by pdtouch** [comment]
This is very helpful. Thank you very much.
